/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carreracaballos;

import javax.swing.JLabel;

/**
 *
 * @author santi
 */
public class frmCarreraCaballos extends javax.swing.JFrame {

    /**
     * Creates new form frmCarreraCaballos
     */
    public frmCarreraCaballos() {
        initComponents();
    }

    public JLabel getlblCaballo1() {
        return lblCaballo1;
    }

    public JLabel getlblCaballo2() {
        return lblCaballo2;
    }

    public JLabel getlblCaballo3() {
        return lblCaballo3;
    }
     public JLabel getlblCaballo4() {
        return lblCaballo4;
    }
      public JLabel getlblCaballo5() {
        return lblCaballo5;
    }
       public JLabel getlblCaballo6() {
        return lblCaballo6;
    }

    public JLabel getlblMeta() {
        return lblMeta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMeta = new javax.swing.JLabel();
        lblCaballo1 = new javax.swing.JLabel();
        lblCaballo2 = new javax.swing.JLabel();
        lblCaballo3 = new javax.swing.JLabel();
        lblCaballo4 = new javax.swing.JLabel();
        lblCaballo5 = new javax.swing.JLabel();
        lblCaballo6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMeta.setBackground(new java.awt.Color(204, 0, 0));
        lblMeta.setText("META");

        lblCaballo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        lblCaballo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carreracaballos/587172f57b7f6103e35c6cc1_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCaballo1)
                    .addComponent(lblCaballo2)
                    .addComponent(lblCaballo5)
                    .addComponent(lblCaballo3)
                    .addComponent(lblCaballo4)
                    .addComponent(lblCaballo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 577, Short.MAX_VALUE)
                .addComponent(lblMeta)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCaballo1)
                .addGap(35, 35, 35)
                .addComponent(lblCaballo2)
                .addGap(27, 27, 27)
                .addComponent(lblCaballo5)
                .addGap(18, 18, 18)
                .addComponent(lblCaballo3)
                .addGap(18, 18, 18)
                .addComponent(lblCaballo4)
                .addGap(30, 30, 30)
                .addComponent(lblCaballo6)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel1.setText("CARRERA DE CABALLOS");

        jButton1.setText("EMPEZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lblCaballo1.setLocation(0, lblCaballo1.getLocation().y);
        lblCaballo2.setLocation(0, lblCaballo2.getLocation().y);
        lblCaballo3.setLocation(0, lblCaballo3.getLocation().y);
        lblCaballo4.setLocation(0, lblCaballo4.getLocation().y);
        lblCaballo5.setLocation(0, lblCaballo5.getLocation().y);
        lblCaballo6.setLocation(0, lblCaballo6.getLocation().y);
        Carrera hilo1 = new Carrera(lblCaballo1, this);
        Carrera hilo2 = new Carrera(lblCaballo2, this);
        Carrera hilo3 = new Carrera(lblCaballo3, this);
        Carrera hilo4 = new Carrera(lblCaballo4, this);
        Carrera hilo5 = new Carrera(lblCaballo5, this);
        Carrera hilo6 = new Carrera(lblCaballo6, this);
        hilo1.start();
        hilo2.start();
        hilo3.start();
        hilo4.start();
        hilo5.start();
        hilo6.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarreraCaballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarreraCaballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarreraCaballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarreraCaballos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarreraCaballos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCaballo1;
    private javax.swing.JLabel lblCaballo2;
    private javax.swing.JLabel lblCaballo3;
    private javax.swing.JLabel lblCaballo4;
    private javax.swing.JLabel lblCaballo5;
    private javax.swing.JLabel lblCaballo6;
    private javax.swing.JLabel lblMeta;
    // End of variables declaration//GEN-END:variables
}
